# basic options
title: Sample Site
author: Rob Foulkrod
email: your-email@domain.com
description: A wonderful site
twitter_username: robfoulk
github_username:  robfoulk

# Build settings
markdown: kramdown
theme: minima
